format = """
$status\
${custom.icon}\
[](bg:#292d3e fg:#9966ff)\
[](bg:#66ccff fg:#292d3e)\
$directory\
[](bg:#292d3e fg:#66ccff)\
[](bg:#66ff99 fg:#292d3e)\
$time\
[](bg:#292d3e fg:#66ff99)\
[](bg:#ffe666 fg:#292d3e)\
$cmd_duration\
[](bg:#292d3e fg:#ffe666)\
[](bg:#ff6680 fg:#292d3e)\
$git_branch\
$git_status\
[ ](fg:#ff6680)\
"""

[status]
style = "fg:#292d3e bg:#9966ff"
symbol = ""
success_symbol = ""
format = '[ $symbol ]($style)'
map_symbol = false
disabled = false

[username]
show_always = false
style_user = "bg:#9966ff"
style_root = "bg:#9966ff"
format = '[$user]($style)'

[hostname]
ssh_only = false
format = "[@$hostname ](bg:#9966ff)"
trim_at = "."
disabled = true

[custom.arch]
description = "Display arch logo"
when = "true"
style = "fg:#292d3e bg:#9966ff"
format = '[$symbol(bg:#9966ff)]($style) '
symbol = " "

[custom.icon]
description = "Display icon for each home folder"
command = """
if [[ "$PWD" = "$HOME" ]]; then
    echo "󰋜 "
elif [[ "$PWD" = "$HOME/Documents" ]]; then
    echo " "
elif [[ "$PWD" = "$HOME/Downloads" ]]; then
    echo "ﲐ "
elif [[ "$PWD" = "$HOME/Music" ]]; then
    echo " "
elif [[ "$PWD" = "$HOME/Pictures" ]]; then
    echo " "
elif [[ "$PWD" = "$HOME/Videos" ]]; then
    echo " "
elif [[ "$PWD" = "$HOME/.local/bin" ]]; then
    echo " "
else
    echo " "
fi
"""
when = "true"
style = "bold fg:#292d3e bg:#9966ff"
format = '[ $output  ]($style)'

[directory]
style = "bold fg:#292d3e bg:#66ccff"
format = '[ $path ]($style)[$read_only]($read_only_style)'
truncation_length = 3
truncation_symbol = ".../"
read_only = '🔒'
read_only_style = "bold fg:#292d3e bg:#66ccff"
use_os_path_sep = true
home_symbol = "~"
truncate_to_repo = true

[git_branch]
symbol = "   "
style = "bold fg:#292d3e bg:#ff6680"
format = '[ $symbol $branch]($style)'

[git_status]
style = "bold fg:#292d3e bg:#ff6680"
format = '[ ($all_status) ]($style)'

[custom.docker]
description = "Shows the docker symbol if the current directory has Dockerfile or docker-compose.yml files"
style = "bg:#ffe666"
format = '[$symbol]($style)'
symbol = " 🐳 "
files = ["Dockerfile", "docker-compose.yml", "docker-compose.yaml"]
when = """ command -v docker &> /dev/null; exit (echo $?); """
disabled = true

[cmd_duration]
min_time = 500
style = "fg:#292d3e bg:#ffe666"
format = "[ 󰔛 $duration ]($style)"
disabled = true

[time]
disabled = true
time_format = "%l:%M %P"
style = "fg:#292d3e bg:#66ff99"
format = '[ $time ]($style)'
