format = """
$status\
${custom.icon}\
[](bg:#292d3e fg:#d8e2dc)\
[](bg:#ffcad4 fg:#292d3e)\
$directory\
[](bg:#292d3e fg:#ffcad4)\
[](bg:#ffe5d9 fg:#292d3e)\
$time\
[](bg:#292d3e fg:#ffe5d9)\
[](bg:#f4acb7 fg:#292d3e)\
$cmd_duration\
[](bg:#292d3e fg:#f4acb7)\
[](bg:#ffddd2 fg:#292d3e)\
$git_branch\
$git_status\
[ ](fg:#ffddd2)\
"""

[status]
style = "fg:#292d3e bg:#d8e2dc"
symbol = ""
success_symbol = ""
format = '[ $symbol ]($style)'
map_symbol = false
disabled = false

[username]
show_always = false
style_user = "bg:#d8e2dc"
style_root = "bg:#d8e2dc"
format = '[$user]($style)'

[hostname]
ssh_only = false
format = "[@$hostname ](bg:#d8e2dc)"
trim_at = "."
disabled = true

[custom.arch]
description = "Display arch logo"
when = "true"
style = "fg:#292d3e bg:#d8e2dc"
format = '[$symbol(bg:#d8e2dc)]($style) '
symbol = " "

[custom.icon]
description = "Display icon for each home folder"
command = """
if [[ "$PWD" = "$HOME" ]]; then
    echo "󰋜 "
elif [[ "$PWD" = "$HOME/Documents" ]]; then
    echo " "
elif [[ "$PWD" = "$HOME/Downloads" ]]; then
    echo "ﲐ "
elif [[ "$PWD" = "$HOME/Music" ]]; then
    echo " "
elif [[ "$PWD" = "$HOME/Pictures" ]]; then
    echo " "
elif [[ "$PWD" = "$HOME/Videos" ]]; then
    echo " "
elif [[ "$PWD" = "$HOME/.local/bin" ]]; then
    echo " "
else
    echo " "
fi
"""
when = "true"
style = "bold fg:#292d3e bg:#d8e2dc"
format = '[ $output  ]($style)'

[directory]
style = "bold fg:#292d3e bg:#ffcad4"
format = '[ $path ]($style)'
truncation_length = 6
truncation_symbol = ".../"
use_os_path_sep = true
home_symbol = "~"
truncate_to_repo = true

[git_branch]
symbol = " "
style = "bold fg:#292d3e bg:#ffddd2"
format = '[ $symbol $branch]($style)'

[git_status]
style = "bold fg:#292d3e bg:#d8e2dc"
format = '[ ($all_status) ]($style)'

[custom.docker]
description = "Shows the docker symbol if the current directory has Dockerfile or docker-compose.yml files"
style = "bg:#f4acb7"
format = '[$symbol]($style)'
symbol = " 🐳 "
files = ["Dockerfile", "docker-compose.yml", "docker-compose.yaml"]
when = """ command -v docker &> /dev/null; exit (echo $?); """
disabled = true

[cmd_duration]
min_time = 500
style = "fg:#292d3e bg:#f4acb7"
format = "[ 󰔛 $duration ]($style)"
disabled = true

[time]
disabled = true
time_format = "%l:%M %P"
style = "fg:#292d3e bg:#ffe5d9"
format = '[ $time ]($style)'
